apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  loadBalancerIP: 192.168.0.9
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8123
  selector:
    kubevirt.io/vm: homeassistant
  type: LoadBalancer
