apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: multus
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab/argocd/metallb/overlays/lab
    repoURL: https://github.com/phoracek/noplacelikehome.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    jsonPointers:
    # Can't make it sync without this
    - /spec/conversion/webhook/clientConfig/caBundle
