- hosts: 127.0.0.1
  connection: local
  vars:
    workstation: false
    full_name: "Petr Horáček"
    email: "phoracek@redhat.com"
  tasks:
  - name: Collect non-root username
    shell: whoami
    register: whoami_result
# -- Git -----------------------------------------------------------------------
  - name: Git
    block:
    - name: Install Git
      dnf:
        name: git
        state: present
      become: true
    - name: Configure global variables
      git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      with_items:
        - { name: "user.name",  value: "{{ full_name }}" }
        - { name: "user.email", value: "{{ email }}" }
        - { name: "pull.ff", value: "only" }
# -- Zsh -----------------------------------------------------------------------
  - name: Zsh
    block:
    - name: Install Zsh
      dnf:
        name: zsh
        state: present
      become: true
    - name: Install oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh
    - name: Configure Zsh
      copy:
        src: ./zsh/zshrc
        dest: ~/.zshrc
    - name: Install zsh profile
      copy:
        src: ./zsh/zprofile
        dest: ~/.zprofile
    - name: Initialize profile directory
      file:
        path: ~/.zprofile.d
        state: directory
    - name: Initialize zshrc directory
      file:
        path: ~/.zshrc.d
        state: directory
    - name: Install custom theme for workstation
      copy:
        src: ./zsh/petr-workstation.zsh-theme
        dest: ~/.oh-my-zsh/themes/petr.zsh-theme
      when: workstation
    - name: Install custom theme for server
      copy:
        src: ./zsh/petr-server.zsh-theme
        dest: ~/.oh-my-zsh/themes/petr.zsh-theme
      when: not workstation
    - name: Set Zsh as the default shell
      user:
        name: "{{ whoami_result.stdout }}"
        shell: /usr/bin/zsh
      become: true
# -- Go ------------------------------------------------------------------------
  - name: Go
    block:
    # TODO: Only if not installed yet
    - name: Install Go from released binaries
      unarchive:
        src: https://golang.org/dl/go1.15.2.linux-amd64.tar.gz
        dest: /usr/local
        remote_src: yes
      become: true
# -- C -------------------------------------------------------------------------
  - name: C
    block:
    - name: Install C Development Tools and Libraries
      shell: dnf groupinstall -y "C Development Tools And Libraries"
      become: true
# -- Rust ----------------------------------------------------------------------
  - name: Rust
    block:
    - name: Install gcc for rust libraries
      dnf:
        name: gcc
        state: present
      become: true
    - name: Install Rust and Cargo
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
# -- Virtualization ------------------------------------------------------------
  - name: Virtualization
    when: workstation
    block:
    - name: Install virt-manager
      dnf:
        name: virt-manager
        state: present
      become: true
    - name: Add user to the libvirt group
      user:
        name: "{{ whoami_result.stdout }}"
        group: libvirt
      become: true
# -- Development VM ------------------------------------------------------------
  - name: Development VM
    when: workstation
    block:
    - name: Install Vagrant
      dnf:
        name:
        - vagrant
        - vagrant-libvirt
        - vagrant-sshfs
        state: present
      become: true
    - name: Install rsync needed for synchronization on Vagrant
      dnf:
        name: rsync
        state: present
      become: true
    - name: Push development VM Vagrantfile to the root of code
      copy:
        src: ./dev/Vagrantfile
        dest: ~/code
    - name: Push venter script under code diretory
      copy:
        src: ./dev/venter.sh
        dest: ~/code/venter.sh
        mode: u+x
    - name: Set an alias to venter
      copy:
        src: ./dev/zshrc
        dest: ~/.zshrc.d/vagrant
# -- Sway ----------------------------------------------------------------------
  - name: Sway
    when: workstation
    block:
    - name: Install Sway module
      command: dnf module install -y sway/full
      become: true
    - name: Fix Sway by adding sticky bit to its binary
      file:
        path: /usr/bin/sway
        state: file
        mode: u+s,g+s,o+s
      become: true
    - name: Initialize sway configuration directory
      file:
        path: ~/.config/sway
        state: directory
    - name: Set Sway configuration
      copy:
        src: ./sway/config
        dest: ~/.config/sway/config
    - name: Set Sway status bar
      copy:
        src: ./sway/status.sh
        dest: ~/.config/sway/status.sh
        mode: u+x
    - name: Start sway when logging in
      copy:
        src: ./sway/profile
        dest: ~/.zprofile.d/sway
    - name: Build the backlight executable
      command: ~/.cargo/bin/rustc ./sway/backlight.rs -o /tmp/backlight
    - name: Move backlight under PATH, set root as the owner of backlight and enable sticky bit
      copy:
        src: /tmp/backlight
        dest: /usr/bin/backlight
        owner: root
        group: root
        mode: u+sx,g+sx,o+sx
      become: true
    - name: Change the splash screen so it shows only text
      shell: plymouth-set-default-theme details -R
      become: true
    - name: Install alsa-utils to get amixer needed to control sound
      dnf:
        name: alsa-utils
        state: present
      become: true
# -- Emacs ---------------------------------------------------------------------
  - name: Emacs
    when: workstation
    block:
    - name: Install Emacs
      dnf:
        name: emacs
        state: present
      become: true
    - name: Enable Emacs as a daemon
      systemd:
        name: emacs
        state: started
        enabled: true
        scope: user
    - name: Fetch Doom Emacs repo
      git:
        repo: https://github.com/hlissner/doom-emacs.git
        dest: ~/.emacs.d
        depth: 1
    - name: Install Doom Emacs
      shell: yes | ~/.emacs.d/bin/doom install
    - name: Apply Doom Emacs config.el
      template:
        src: ./emacs/config.el.j2
        dest: ~/.doom.d/config.el
    - name: Apply Doom Emacs init.el
      copy:
        src: ./emacs/init.el
        dest: ~/.doom.d/init.el
    - name: Apply Doom Emacs packages.el
      copy:
        src: ./emacs/packages.el
        dest: ~/.doom.d/packages.el
    - name: Sync Doom Emacs configuration
      shell: yes | ~/.emacs.d/bin/doom sync
    - name: Install cmake for terminal plugin
      dnf:
        name: cmake
        state: present
      become: true
    - name: Install Iosevka SS05 fonts
      block:
      - name: Install unzip to be able to extract downloaded fonts
        dnf:
          name: unzip
          state: present
        become: true
      - name: Check whether the font is already installed
        stat:
          path: /usr/share/fonts/iosevka
        register: iosevka_directory
      - name: Create directory for Iosevka font
        when: not iosevka_directory.stat.exists
        file:
          path: /usr/share/fonts/iosevka
          state: directory
        become: true
      - name: Download Iosevka fonts into system fonts directory
        when: not iosevka_directory.stat.exists
        unarchive:
          src: https://github.com/be5invis/Iosevka/releases/download/v3.6.3/pkg-iosevka-ss05-3.6.3.zip
          dest: /usr/share/fonts/iosevka
          remote_src: yes
        become: true
      - name: Refresh system fonts
        shell: fc-cache
# -- Workstation utils ---------------------------------------------------------
  - name: Workstation utils
    when: workstation
    block:
    - name: Allow sound control, input and output
      dnf:
        name:
        - pulseaudio
        - pavucontrol-qt
        state: present
      become: true
    - name: Install file manager
      dnf:
        name:
        - pcmanfm
      become: true
    - name: Ensure that configuration folder exists
      file:
        path: ~/.config/pcmanfm/default
        state: directory
    - name: Configure file manager
      copy:
        src: ./pcmanfm/pcmanfm.conf
        dest: ~/.config/pcmanfm/default/pcmanfm.conf
    - name: Install password manager
      dnf:
        name:
        - keepassxc
        state: present
      become: true
# -- Firefox -------------------------------------------------------------------
  - name: Firefox
    when: workstation
    block:
    - name: Install Firefox
      dnf:
        name: firefox
        state: present
      become: true
