---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  addresses:
  - 192.168.0.2-192.168.0.9
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: config
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "11"
