---
- name: Install base packages
  hosts: server
  become: yes
  tasks:
    - name: Install podman, git and tmux
      ansible.builtin.dnf:
        name:
          - podman
          - git
          - tmux
        state: present
