---
- name: Install automatic updates
  hosts: server
  become: yes
  tasks:
    - name: Install dnf-automatic
      ansible.builtin.dnf:
        name: dnf-automatic
        state: latest

    - name: Enable a timer unit for dnf-automatic
      ansible.builtin.systemd_service:
        name: dnf-automatic.timer
        state: started
        enabled: true
