apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: iot-network
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "iot-network", 
      "type": "bridge", 
      "bridge": "br0", 
      "macspoofchk": true, 
      "disableContainerInterface": true,
      "preserveDefaultVlan": false 
    }

