export ZSH="/home/phoracek/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git rust fancy-ctrl-z dnf)
source $ZSH/oh-my-zsh.sh

source "$HOME/.cargo/env"
export PATH="$PATH:$HOME/.local/bin"
export GOROOT="$HOME/.local/go"
export GOPATH="$HOME/go"
export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
export EDITOR='hx'

# Quick jumps to projects
alias kaseta='cd ~/code/zlosynth/kaseta'
alias daisy='cd ~/code/zlosynth/daisy'
alias proton='cd ~/code/zlosynth/proton'
alias achordion='cd ~/code/zlosynth/achordion'
alias zlosynth.github.io='cd ~/code/zlosynth/zlosynth.github.io'
alias noplacelikehome='cd ~/noplacelikehome'
