# oh-my-zsh configuration
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="petr"
DISABLE_UNTRACKED_FILES_DIRTY="true"
source $ZSH/oh-my-zsh.sh

# User config
path+=("$HOME/.cargo/bin")
path+=("/usr/local/go/bin")
export PATH

if [ "$(ls -A ~/.zshrc.d)" ]; then
    for f in ~/.zshrc.d/*; do
        source ${f}
    done
fi
